// AUTO-GENERATED by scripts/dumpStateLegislators.ts
// Run "npx tsx scripts/dumpStateLegislators.ts" to refresh (do after each November election)
// Empty until the overnight dump runs — service falls back to OpenStates API until then.

import type { StateRepresentative } from '../services/openStates'

export const STATE_LEGISLATORS: Record<string, StateRepresentative[]> = {}