/**
 * One-time (and nightly) script to dump all 50 state legislatures from OpenStates
 * into a static TypeScript file — eliminating runtime API dependency.
 *
 * Run with:  npx tsx scripts/dumpStateLegislators.ts
 *
 * Output:    src/data/stateLegislators.ts
 *
 * Safe to re-run anytime. Uses the full 250 req/day budget since this is a
 * controlled offline script, not a user-facing request. Takes ~5 minutes.
 */

import 'dotenv/config'
import { writeFileSync } from 'fs'
import { join } from 'path'

const BASE_URL = 'https://v3.openstates.org'
const API_KEY = process.env.OPENSTATES_API_KEY ?? ''
const OUT_FILE = join(__dirname, '../src/data/stateLegislators.ts')

const US_STATES = [
  'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA',
  'KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ',
  'NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT',
  'VA','WA','WV','WI','WY',
]

interface Rep {
  id: string
  name: string
  party: string
  title: string
  chamber: string
  district: string
  imageUrl: string | null
  profileUrl: string | null
  email: string | null
}

async function fetchChamber(state: string, chamber: 'upper' | 'lower'): Promise<Rep[]> {
  const results: Rep[] = []
  let page = 1
  let maxPage = 1

  while (page <= maxPage && page <= 5) {
    const url = `${BASE_URL}/people?jurisdiction=ocd-jurisdiction/country:us/state:${state}/government&org_classification=${chamber}&per_page=50&page=${page}`
    const res = await fetch(url, { headers: { 'X-API-KEY': API_KEY } })

    if (res.status === 429) {
      console.error(`  [${state}/${chamber}] 429 — daily limit hit. Stopping.`)
      process.exit(1) // fail fast so we know exactly where we stopped
    }

    if (!res.ok) {
      console.warn(`  [${state}/${chamber}] HTTP ${res.status} on page ${page} — stopping chamber`)
      break
    }

    const json = await res.json() as any
    maxPage = json.pagination?.max_page ?? 1

    for (const p of json.results ?? []) {
      if (!p.current_role) continue
      results.push({
        id: p.id,
        name: p.name,
        party: typeof p.party === 'string' ? p.party : (p.party?.[0]?.name ?? 'Unknown'),
        title: chamber === 'upper' ? 'Senator' : 'Representative',
        chamber,
        district: String(p.current_role?.district ?? ''),
        imageUrl: p.image ?? null,
        profileUrl: (p.links ?? [])[0]?.url ?? null,
        email: null,
      })
    }

    page++
    // 500ms between pages within a state — well-behaved
    if (page <= maxPage) await sleep(500)
  }

  return results
}

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)) }

async function main() {
  if (!API_KEY) {
    console.error('OPENSTATES_API_KEY not set in .env')
    process.exit(1)
  }

  const all: Record<string, Rep[]> = {}
  let totalRequests = 0

  for (const state of US_STATES) {
    process.stdout.write(`${state}... `)
    const upper = await fetchChamber(state.toLowerCase(), 'upper')
    totalRequests += Math.ceil(upper.length / 50) || 1
    await sleep(1000)

    const lower = await fetchChamber(state.toLowerCase(), 'lower')
    totalRequests += Math.ceil(lower.length / 50) || 1

    const reps = [...upper, ...lower].sort((a, b) => {
      if (a.chamber !== b.chamber) return a.chamber === 'upper' ? -1 : 1
      return a.name.localeCompare(b.name)
    })

    all[state] = reps
    console.log(`${upper.length} senators, ${lower.length} reps (${totalRequests} req total)`)

    // 2 seconds between states — ~5 min total for all 50
    await sleep(2000)
  }

  const totalLegislators = Object.values(all).reduce((s, v) => s + v.length, 0)
  const generated = new Date().toISOString()

  const lines = [
    `// AUTO-GENERATED by scripts/dumpStateLegislators.ts on ${generated}`,
    `// Run "npx tsx scripts/dumpStateLegislators.ts" to refresh (do after each November election)`,
    `// ${totalLegislators} legislators across 50 states — no runtime API calls needed`,
    ``,
    `import type { StateRepresentative } from '../services/openStates'`,
    ``,
    `export const STATE_LEGISLATORS: Record<string, StateRepresentative[]> = {`,
  ]

  for (const state of US_STATES) {
    lines.push(`  ${state}: ${JSON.stringify(all[state], null, 4).replace(/^/gm, '  ').trim()},`)
  }

  lines.push(`}`)
  lines.push(``)

  writeFileSync(OUT_FILE, lines.join('\n'), 'utf8')
  console.log(`\nWrote ${totalLegislators} legislators to ${OUT_FILE}`)
  console.log(`Total API requests used: ${totalRequests}`)
}

main().catch(err => { console.error(err); process.exit(1) })
